### ISSUE TITLE
Skip-länk saknar mål

### ISSUE THREAD

**Issue by surffilip** [niklasternstedt/niklasternstedt.se#2]
Skip länken hänvisar till id:t `main`, men inget id med det namnet finns. Rimligt hade varit att lägga det på main-elementet tänker jag...
https://github.com/niklasternstedt/niklasternstedt.se/blob/ca7cd42fe1065694e12330498cfb2e149043a1a8/index.html#L33

**Comment by niklasternstedt** [comment]
Aj då, det var slarvigt. Tack för att du hittade det. Fixar det 😄 .

**Comment by niklasternstedt** [comment]
Lade till id main till elementet main.
